@MovieAPI_HostAddress = https://localhost:7150

GET {{MovieAPI_HostAddress}}/api/actors

###

GET {{MovieAPI_HostAddress}}/api/actors/10

###

POST {{MovieAPI_HostAddress}}/api/actors
Content-Type: application/json
{
    "name": "Petter Svensson",
    "birthYear": "1975",
    "movies": null 
}

###

PUT {{MovieAPI_HostAddress}}/api/actors/10
Content-Type: application/json

{
  "actorId": 10,
  "name": "Petterson Sven",
  "birthYear": "1974",
  "movies": null
}

###
POST {{MovieAPI_HostAddress}}/api/movies/2/actors/3
Content-Type: application/json
{

}