@MovieAPI_HostAddress = https://localhost:7150

GET {{MovieAPI_HostAddress}}/api/reviews

###
@id=2

GET {{MovieAPI_HostAddress}}/api/reviews/{{id}}

###
@movieId=2

POST {{MovieAPI_HostAddress}}/api/reviews/{{movieId}}
Content-Type: application/json

{
  "title": "Monty Python's Life of Brian",
  "reviewerName": "Lars Karlqvist",
  "comment": "Nästan rolig... hahaha.",
  "rating": 3
}

###
@id=2

PUT {{MovieAPI_HostAddress}}/api/reviews/{{id}}
Content-Type: application/json

  {
    "title": "Monty Python's Life of Brian",
    "reviewerName": "Adam Brannon",
    "comment": "After last year’s bitterly disappointing Once Upon A Time in Hollywood bla bla.",
    "rating": 4
  }

###
@delid=2
DELETE {{MovieAPI_HostAddress}}/api/reviews/{{delid}}

###
